media: public

content:
  - name: projects
    label: Projects
    type: collection
    path: components/projects
    fields:
      - name: imageSrc
        label: Image
        type: image
        list: false
        required: true
        
      - name: category
        label: Category
        type: select
        required: true
        options:
          values:
          [Entertainment, Industrial, Retail, Spiritual, Stairs, Utulity Structures]
        
      - name: title
        label: Title
        type: string
        required: true
      - name: location
        label: Location
        type: string
        required: true
      - name: client
        label: Client
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
    view:
      fields: [title, category, location, client, description]
      primary: title
      sort: [title]
