media: public

content:
  - name: projects
    label: Projects
    type: collection
    path: src/projects
    fields:
      - name: imageSrc
        label: Image
        type: image
        list: false
        required: true
      - name: category
        label: Category
        type: select
        required: true
        options:
          - Retail
          - Residential
          - Spiritual
          - Entertainment
          - Industrial
          - Stand alone structures
          - Stairs
          - Utility Structures
      - name: title
        label: Title
        type: string
        required: true
      - name: location
        label: Location
        type: string
        required: true
      - name: client
        label: Client
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: duration
        label: Duration
        type: string
        required: true
    view:
      fields: [title, category, location, client, description, duration]
      primary: title
      sort: [title]
