media: public

logos:
  - name: "ABC"
    img: "/logos/abc.png"
  - name: "AUB"
    img: "/logos/aub.png"
  - name: "B018"
    img: "/logos/b018.png"
  - name: "Bentley"
    img: "https://cdn.simpleicons.org/bentley/fff"
  - name: "Cat Group"
    img: "/logos/catgroup.png"
  - name: "City Centre"
    img: "/logos/citycentre.png"
  - name: "City Centre"
    img: "/logos/creditlibanis.png"
  - name: "Four Seasons"
    img: "/logos/fourseasons.png"
    color: "white"
  - name: "Kharafi"
    img: "/logos/kharafi.svg"
  - name: "Lamborghin"
    img: "https://cdn.simpleicons.org/lamborghini"
  - name: "Mitsulift"
    img: "/logos/mitsulift.png"
  - name: "Shindler"
    img: "/logos/shindler.png"