media: public

content:
  - name: projects
    label: Projects
    type: collection
    path: Companies
    fields:
      - name: imageSrc
        label: Image
        type: image
        list: false
        required: true
      - name: category
        label: Category
        type: select
        options:
          - label: Retail
            value: Retail
          - label: Residential
            value: Residential
          - label: Spiritual
            value: Spiritual
          - label: Entertainment
            value: Entertainment
          - label: Industrial
            value: Industrial
          - label: Stand alone structures
            value: Stand alone structures
          - label: Stairs
            value: Stairs
          - label: Utility Structures
            value: Utility Structures
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: location
        label: Location
        type: string
        required: true
      - name: client
        label: Client
        type: string
        required: true
      - name: description
        label: Description
        type: string
        required: true
      - name: duration
        label: Duration
        type: string
        required: true
    view:
      fields: [title, category, location, client, description, duration]
      primary: title
      sort: [title]